### ISSUE TITLE
Postprocessing shader on Group

### ISSUE THREAD

**Issue by fatlinesofcode** [squarefeet/ShaderParticleEngine#122]
I'd like to apply a postprocessing Shader to a SPE Group. The three.js bloom shader to be exact. I can do using EffectComposer on the Scene. However I only want to the shader to be applied to the SPE group not the whole Scene. Is there any other approach I could to apply the shader to the Group of particles only?

**Comment by squarefeet** [comment]
Ah this is an interesting one.

You could render your SPE Group to an FBO (frame-buffer object), apply the post-processing, then combine that with your main render? The technique of using a frame-buffer-object is also called Render-To-Texture (RTT).

Just in case you're not familiar with it, FBO/RTT is the process of rendering to an image instead of the screen. There are plenty of articles/tutorials dotted around the interwebs on how to do this using three.js, so I shan't link to any here. A quick search will get you what you need!
