### ISSUE TITLE
Looks Like Three.js r71 Broke This

### ISSUE THREAD

**Issue by titansoftime** [squarefeet/ShaderParticleEngine#69]
After upgrading to this new release. This amazing particle engine no longer works =[

More than likely due to: https://github.com/mrdoob/three.js/pull/5805

**Comment by squarefeet** [comment]
Balls! What's happening? Can't look into it *right* now, but if you let me know what's going on (errors, if any, or just black screen, etc.) then I can have a look later on.

**Comment by titansoftime** [comment]
Ha, my reaction exactly!

I am at work so I cannot build a test case right now, but I can tell you opacity seems to be broken as well as some fairly psychedelic colors going on.

That PR from three has broken a few custom shader programs I use.

**Comment by squarefeet** [comment]
Ha, you got me at psychedelics. I've just run the basic example using r71 and it's all sorts of crazy. Thing is, now I've done that, I can't not fix it!

Will let you know if I make any progress :)

**Comment by squarefeet** [comment]
All fixed. Turned out not to be due to that pull req on THREE.js, but instead down to how this version seems to handle boolean properties in Material instances.

I'll pushed a new release and updated the README. New version is 0.7.9 and is [here](https://github.com/squarefeet/ShaderParticleEngine/releases/tag/Release-0.7.9).

Thanks for letting me know!

**Comment by titansoftime** [comment]
Ah, badass.

You da man!
