### ISSUE TITLE
No Fog Support (or maybe there is and I'm dumb)

### ISSUE THREAD

**Issue by titansoftime** [squarefeet/ShaderParticleEngine#70]
I do not see a way to enable fog. I would do this myself, but shader programming i something that I still suck at.... like bad.

**Comment by squarefeet** [comment]
I think you should be able to enable fog on the `ShaderMaterial` instance that sits within an `SPE.Group` instance:

```javascript

var group = new SPE.Group( ... );
group.material.fog = true;

```

I've not tested this, though. And I'm still assuming that the shader code within THREE.js hasn't changed too much (apart from that pull-req you mentioned before) and that fog is still applied *after* my shader code...

**Comment by titansoftime** [comment]
After trying this, I added ```fogDensity``` and ```fogColor``` to the shader uniforms (bugged out otherwise).

```
    // Create uniforms
    that.uniforms = {
        duration:       { type: 'f',    value: that.maxAge },
        texture:        { type: 't',    value: that.texture },
        hasPerspective: { type: 'i',    value: that.hasPerspective },
        colorize:       { type: 'i',    value: that.colorize },
	    fogColor:       { type: "c",    value: new THREE.Color( 0x000000 ) } ,
	    fogDensity:     { type: "f",    value: 0.08 }
    };
```

elsewhere:
```
var group = new SPE.Group( ... );
group.material.fog = true;
```

 It does not seem to work.

**Comment by squarefeet** [comment]
Hmmmm....

I'll have to take a look at this later, it's past midnight here and sleep is calling. I'll take a look at the docs and source for Fog in THREE.js and see if I can figure something out.

**Comment by titansoftime** [comment]
Awesome man. Thanks for being on it.

**Comment by squarefeet** [comment]
No worries. Worst case scenario is that I'll have to add my own fog calculations to the shader, but that should be pretty straightforward.

**Comment by titansoftime** [comment]
I also use Jbouny's ocean shader and they added fog by adding


```
THREE.ShaderChunk[ "common" ],
THREE.ShaderChunk[ "fog_pars_fragment" ],
```

Above the ```void main()```

And 

```THREE.ShaderChunk[ "fog_fragment" ],```

right above ```'gl_FragColor = blah;```

in the fragment shader.

This did not work here, but maybe something similar? Anyway that's all I got,

**Comment by Usnul** [comment]
I'd be a bit careful about inserting shader chunks, i've had problems going from r70 to r71 as content of chunks is not frozen across three.js versions it seems. Also, have to be careful about defines. Would be nice to eventually just plug an extra chunk into Three.js particle shader to alter size/color/position from compatibility stand-point.

**Comment by squarefeet** [comment]
@titansoftime I've finally found a little time to spend sprucing up this project, and I've put in Fog support on the `dev` branch. Give it a whirl and let me know of any issues and I'll fix 'em up before I promote to `master`. I've only tested this with three.js r71 so far...

@Usnul You'll probably chastise me for this, but I used THREE's ShaderChunks for this. Since you mentioned `define`s, I must also mention that I swapped out `hasPerspective` and `colorize` to use `define`s rather than `uniform`s. It feels nicer, but I'd like to know why you feel one should be careful with define statements?

**Comment by titansoftime** [comment]
Ok I tested with 71 and 70

70: No errors but no fog support

71: No particles. Errors:
```THREE.WebGLShader: gl.getShaderInfoLog() ERROR: 0:101: 'square' : no matching overloaded function found ```
```ERROR: 0:101: 'square' : no matching overloaded function found ```
```ERROR: 0:101: 'LOG2' : undeclared identifier ```
```ERROR: 0:102: 'whiteCompliment' : no matching overloaded function found```

I haven't ran an isolated test yet.

**Comment by Usnul** [comment]
@squarefeet 
defines need to be inserted at the head of the shader at some point, three.js does this for you in most cases that it deals with, that's the only concern I really have. Smaller concern would be delegation of something to preprocessor that we could do ourselves, but I don't see that as much of an issue, glsl compiler should be quite performant regardless of platform.
As far as shader chunks go - i think it's a good way to go, as you get to replicate behaviour of THREE materials to an extent you care at very low effort cost.
I still do think that simulation and rendering should be quite well separated, so that if one wishes - they could use a different rendering pipeline while still taking advantage of particle simulation.

**Comment by squarefeet** [comment]
@titansoftime What GPU do you have?

**Comment by squarefeet** [comment]
@titansoftime Just pushed a possible fix to `dev` - give it a shot when you get a chance and let me know if it helps.

**Comment by titansoftime** [comment]
@squarefeet Works perfect. Nice!
