### ISSUE TITLE
Typescript declaration & npm access

### ISSUE THREAD

**Issue by AndyTyurin** [squarefeet/ShaderParticleEngine#74]
Hey!

Currently I'm working on my threeJS 2.5D space game and transfering my project to Typescript for easily scaling.
I used shader particle engine and noticed that it hasn't any good declaration file to use it in typescript. Also as I think SPE not published on npmjs.com, it will be great if it would be here.

For now I'm writing my own declaration file for ShaderParticleEngine and want to publish it when it will be completed.

What do you think about that, can you publish current version of SPE to npmjs.com?
It been cool to load your module like:
```
npm i spe
```

Regards, Andy Tyurin.

**Comment by AndyTyurin** [comment]
Currently under development, but I leave it here https://github.com/AndyTyurin/spe-declaration
=-)

**Comment by squarefeet** [comment]
Hey @AndyTyurin,

Huge apologies for the massive delay in getting back to you on this! I didn't incorporate it at the time because I was planning a rewrite, and a fair bit might change. The rewrite is almost done now (see #75), so when the new version is fully complete and I get a sec, I'll grab your `spe-declaration`, update it, and whack it in the repo (with full credits, and your permission of course).

Cheers.

**Comment by squarefeet** [comment]
v1.0.0 is available on NPM!

https://www.npmjs.com/package/shader-particle-engine
